# Generated by Django 4.2.7 on 2025-10-09 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL', max_length=2000, verbose_name='original URL')),
                ('short_code', models.CharField(blank=True, help_text='Leave blank to generate a random code', max_length=20, unique=True, verbose_name='short code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for URLs that never expire', null=True, verbose_name='expires at')),
                ('is_custom', models.BooleanField(default=False, help_text='Whether this URL uses a custom short code', verbose_name='is custom')),
                ('title', models.CharField(blank=True, help_text='Optional title for the URL', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Optional description for the URL', verbose_name='description')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for the URL', max_length=500, verbose_name='tags')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this URL is active', verbose_name='is active')),
                ('password', models.CharField(blank=True, help_text='Optional password to protect the URL', max_length=128, verbose_name='password')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='click count')),
                ('last_clicked', models.DateTimeField(blank=True, null=True, verbose_name='last clicked')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='clicked at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('referrer', models.URLField(blank=True, verbose_name='referrer')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='device type')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='browser')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='operating system')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.url', verbose_name='URL')),
            ],
            options={
                'verbose_name': 'click',
                'verbose_name_plural': 'clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_code'], name='shortener_u_short_c_50dfff_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['created_by'], name='shortener_u_created_9a9a58_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['is_active'], name='shortener_u_is_acti_5569c6_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['expires_at'], name='shortener_u_expires_e57f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['url'], name='shortener_c_url_id_e78f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['clicked_at'], name='shortener_c_clicked_5992aa_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip_address'], name='shortener_c_ip_addr_95b12d_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['country'], name='shortener_c_country_95f649_idx'),
        ),
    ]
